#ifndef ENEMY_SPRITE_H
#define ENEMY_SPRITE_H
typedef enum {
  ENEMY_INACTIVE = 0,
  ENEMY_WALKING,
  ENEMY_IDLE,
  ENEMY_TAKE_DEMAGE,
  ENEMY_DYING,
  ENEMY_SPAWNING,
  ENEMY_DEAD,
  ENEMY_PROCESSES_ACTING_FORCES,
  SIZE_ENEMY_STATE_ID,
} EnemyStateID;

typedef enum {
  ENEMY_NONE = 0,
  GOBLIN,
  SKELLETON,
  BAT,
  SIZE_ENEMY_SPRITE_ID,
} EnemySpriteID;

#endif // !ENEMY_SPRITE_H
