#ifndef MUMBLE_SPRITE_H
#define MUMBLE_SPRITE_H
typedef enum {
  MUMBLE_INACTIVE = 0,
  CASTING_MUMBLE,
  MUMBLE_MOVE_TO_TARGET,
  MUMBLE_HIT_TARGET,
  MUMBLE_COOLDOWN,
  SIZE_MUMBLE_STATE_ID,
} MumbleStateID;

typedef enum {
  MUMBLE_NONE = 0,
  FIREBALL,
  SIZE_MUMBLE_SPRITE_ID,
} MumbleSpriteID;
#endif // !MUMBLE_SPRITE_H
